ktor:
    application:
        modules:
            - bookstore.playground.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost/member-manager"
  user: member-manager
  password: dev-password