services:
  postgres:
    image: postgres:17.4-bookworm
    environment:
      POSTGRES_USER: member-manager
      POSTGRES_PASSWORD: dev-password
      POSTGRES_DB: member-manager
    ports:
      - "5432:5432"
    volumes:
      - "./postgres:/docker-entrypoint-initdb.d"